---
# run with 'docker-compose up --exit-code-from test'
version: '2'
services:
  test:
    image: alpine
    command: wget web:80
    depends_on:
    - web
  web:
    ports: 
    - '80:80'
    image: nginx:latest
